FROM node:20-bullseye

COPY front /app
COPY libs /libs

WORKDIR /app

RUN npm install
RUN npm run build

# Hack
RUN cp -r /libs/node_modules/.prisma /app/node_modules

EXPOSE 3000

CMD ["npm", "run", "start"]